# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2.1.0
    
    - name: Setup GIT token
      uses: fregante/setup-git-token@v1
      with:
        # The token provided by GitHub actions via secrets.GITHUB_TOKEN
        token: 
        # The name that will be used as "Author" of future commits
        name: # optional, default is GitHub actions
        # The email that will be used as "Author" of future commits
        email: # optional, default is actions@users.noreply.github.com

    # Runs a single command using the runners shell
    - name: Build
      run: |
        cd $GITHUB_WORKSPACE
        make

#     - name: Upload Artifact
#       uses: actions/upload-artifact@v1.0.0
#       with:
#         name: build.tar.gz
#         path: .
    
    - name: Deploy to pages
      uses: crazy-max/ghaction-github-pages@v1.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        target_branch: kiss.github.io
        keep_history: false
        build_dir: build
        # Write the given domain name to the CNAME file
        # fqdn: # optional 
